version: "2.1"
services:
  postgresdb:
    container_name: postgresdb
    image: dig-grid-artifactory.apps.ge.com/virtual-docker/acid/spilo-cdp-12:1.6-p128
    restart: on-failure
    user: root
    ports:
      - "5432:5432"
    environment:
      PGUSER_ADMIN: postgresadmin
      PGPASSWORD_ADMIN: postgresdb
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: postgresdb
    volumes:
      - ieee2030postgresql:/home/postgres/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$PGUSER_SUPERUSER"]
      interval: 15s
      timeout: 5s
      retries: 5

  postgresdb-init:
    container_name: postgresdb-init
    image: dig-grid-artifactory.apps.ge.com/virtual-docker/acid/spilo-cdp-12:1.6-p128
    restart: on-failure
    user: root
    command: [
        "sh", "-c",
        "sleep 10 && \
         psql postgresql://$${PGUSER_SUPERUSER}:$${PGPASSWORD_SUPERUSER}@$${PG_HOST}:5432 --file=/docker-entrypoint-initdb.d/init-db.sql"
    ]
    environment:
      PGPASSWORD_ADMIN: postgresdb
      PGUSER_SUPERUSER: postgres
      PGPASSWORD_SUPERUSER: postgresdb
      PG_HOST: postgresdb
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
volumes:
  ieee2030postgresql:
    external: false
